# Generated by Django 5.2.16 on 2026-07-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.TextField(null=True)),
                ('market', models.CharField(max_length=8, null=True)),
                ('trade_date', models.DateField()),
                ('close', models.FloatField(null=True)),
                ('change_pct', models.FloatField(null=True)),
                ('pe', models.FloatField(null=True)),
                ('pb', models.FloatField(null=True)),
                ('dividend_yield', models.FloatField(null=True)),
                ('revenue_yoy', models.FloatField(null=True)),
                ('revenue_cum_yoy', models.FloatField(null=True)),
                ('revenue_month', models.CharField(max_length=7, null=True)),
                ('gross_margin', models.FloatField(null=True)),
                ('operating_margin', models.FloatField(null=True)),
                ('eps', models.FloatField(null=True)),
                ('quarter', models.CharField(max_length=6, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock_snapshots',
                'indexes': [models.Index(fields=['code', '-trade_date'], name='stock_snaps_code_7986c3_idx')],
                'constraints': [models.UniqueConstraint(fields=('code', 'trade_date'), name='uniq_stock_snapshot_code_date')],
            },
        ),
    ]
