# Generated by Django 5.2.16 on 2026-07-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTheme',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'research_theme',
            },
        ),
        migrations.CreateModel(
            name='CompanyResearch',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('sector_en', models.CharField(blank=True, default='', max_length=64)),
                ('industry_en', models.CharField(blank=True, default='', max_length=64)),
                ('business_summary', models.TextField(blank=True, default='')),
                ('themes', models.JSONField(default=list)),
                ('source_repo', models.CharField(default='Timeverse/My-TW-Coverage', max_length=128)),
                ('source_commit', models.CharField(blank=True, default='', max_length=40)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_research',
                'indexes': [models.Index(fields=['sector_en'], name='company_res_sector__c6d11a_idx')],
            },
        ),
    ]
